name: shared
description: "Shared utilities and widgets for TiDaro applications."
version: 0.1.0-pre-alpha.3
homepage: https://github.com/neo-tidaro/neo-tidaro
repository: https://github.com/neo-tidaro/neo-tidaro
publish_to: http://localhost:4000

resolution: workspace

environment:
  sdk: "3.9.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
