name: tidaro_mini
description: "A new Flutter project."
publish_to: http://localhost:4000
resolution: workspace
version: 0.1.0-pre-alpha.3
environment:
  sdk: "3.9.0"
  flutter: ">=3.35.0"
dependencies:
  flutter:
    sdk: flutter

  languist:
    path: ../../packages/languist
  ui_kit:
    path: ../../packages/ui_kit
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
flutter:
  uses-material-design: true
