name: tidash
resolution: workspace
description: "TiDaro A Tidy Dashboard for Admins."
publish_to: none
version: 0.1.0-pre-alpha.3
environment:
  sdk: "3.9.0"
  flutter: ">=3.35.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  languist:
    path: ../../packages/languist
  ui_kit:
    path: ../../packages/ui_kit
  shared:
    path: ../../packages/shared
  core:
    path: ../../packages/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
