name: ui_kit
description: "A Fresh UI Kit for Flutter."
publish_to: none
version: 0.0.1
homepage: https://github.com/neo-tidaro/ui_kit
repository: https://github.com/neo-tidaro/ui_kit
resolution: workspace
environment:
  sdk: '3.9.0'
  flutter: '>=3.35.0'
dependencies:
  flutter:
    sdk: flutter
  material_color_utilities: ^0.11.1
  google_fonts: ^6.2.1
  
  languist:
    path: ../languist
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter: