name: core
description: "A Fresh Core for Flutter."
version: 0.1.0-pre-alpha.3
homepage: https://github.com/neo-tidaro/core
repository: https://github.com/neo-tidaro/core
publish_to: http://localhost:4000
resolution: workspace

environment:
  sdk: "3.9.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  # Workspace Dependencies
  shared:
    path: ../shared
  domain:
    path: ../domain
  flutter_dotenv: any
  get_it: any
  fpdart: any
  http: any
  supabase_flutter: any
