name: core
description: "A Fresh Core for Flutter."
version: 0.0.1
homepage: https://github.com/neo-tidaro/core
repository: https://github.com/neo-tidaro/core

resolution: workspace

environment:
  sdk: '3.9.0'
  flutter: '>=3.35.0'

