name: domain
description: "Domain layer for Neo-Tidaro workspace containing business models and entities"
version: 0.1.0-pre-alpha.3
homepage: https://github.com/neo-tidaro/neo-tidaro
repository: https://github.com/neo-tidaro/neo-tidaro
publish_to: none

resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
